apiVersion: v1
kind: Service
metadata:
  name: workprofile-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    # nodePort will be assigned automatically
  selector:
    app: workprofile